### ISSUE TITLE
Nothing happens when pressing Dump Game

### ISSUE THREAD

**Issue by Jakehallmark** [codemasterv/fPKG_Maker_GUI#1]
After putting in correct IP Address, and Add IP, when Dump Game is pressed nothing happens. If I manually run the script from inside the folder the game dumps just fine but nothing happens from inside the app.

**Comment by codemasterv** [comment]
Try the win10 release and let me know if that fixed your issue please

**Comment by codemasterv** [comment]
> After putting in correct IP Address, and Add IP, when Dump Game is pressed nothing happens. If I manually run the script from inside the folder the game dumps just fine but nothing happens from inside the app.

If its still not working you may need to reinstall your wsl ubuntu 20.04 by using the windows store or by running in powershell as admin/

wsl.exe --install -d Ubuntu-20.04

after removing the old install of ubuntu. 

I verified that this is working on windows 10 and windows 11 

Here is a video of it working on windows 10

https://www.youtube.com/watch?v=6IIYGGSWvbg

This is a configuration issue on your side.

If you have further questions or need help you can find me on reddit as /u/mogi_codemasterv

**Comment by Jakehallmark** [comment]
The issue seems to be the program calling yourftpdump.bat, while ftpdump.dat works fine. 

`@ECHO off
%HOMEPATH%\AppData\Local\Microsoft\WindowsApps\ubuntu2004.exe run -e dos2unix yourftpdump
%HOMEPATH%\AppData\Local\Microsoft\WindowsApps\ubuntu2004.exe run -e ./yourftpdump %*`

causes the cmd window to open and flash closed with nothing happening.

`wsl -e ./ftpdump %*`

actually starts the dump process but the GUI doesn't seem to mess with ftpdump and instead edits the yourftpdump file. That seems to be causing the issue, at least for me.  If I just remove the yourftpdump and rename the ftpdump it works fine from the GUI, especially since the settings files are identical it's the commands in the .bat that is not working.
