### ISSUE TITLE
orbis-pub-cmd.exe gets stuck for unknown reason

### ISSUE THREAD

**Issue by shinji257** [codemasterv/fPKG_Maker_GUI#3]
Monitoring processes any way I can (right now via Resource Monitor and Procexp.exe) it seems that orbis-pub-cmd.exe gets stuck when building the fpkg.  So far this is only happening on building the game fpkg and I don't know why.  I run the same command line from a command prompt and it works fine there.

I guess I'll have to wait until you get a visual up for me but having the actual command prompt window it runs in visible will help to see if there is some kind of weird error that appears causing this.  Alternatively having command output sent to a text file would be useful as well.

**Comment by codemasterv** [comment]
Added log window and fixed path errors and general bug fixes. 

Try the latest release and let me know if that fixed your issues

**Comment by shinji257** [comment]
Can't run the latest release.  Get a message saying that the app can't run on this PC and the file is only 1KB in size.

**Comment by shinji257** [comment]
Ok.  I ran it and it still gets jammed up.  I started it up last night and the process never exited even though it had long been done doing what it needed to do.  This is further confirmed by the fact that after killing it manually the log that showed up in the log box indicated it was done.

With that said I still don't know why it seems to stall after completing without actually exiting properly.  Your call to ftpdump via wsl never has the issue.  Maybe generate a batch file on demand and try calling that and seeing if that resolves the issue?  Try a different execution method?  Just throwing out ideas from a non-programmer.

It might be because it is a long running process as well.  For some reason the patch fpkg builds have no issues.

**Comment by shinji257** [comment]
Second thing I noticed (and this is cosmetic... now that I know it happens) is that the contents of the log is repeated.

Note this gist log.  It's the full contents of the log window.  You can see where it repeats, and the second set is identical to the first set.  This isn't two runs, and your log window clears when a new task is started anyways.

https://gist.github.com/shinji257/a25a51498e013a06f808127f5209094e

**Comment by codemasterv** [comment]
Fixed the double log print issue and the lock up issue should now be fixed. Lockup was because of a large resource file.

If the .exe shows up as 1kb you can download it directly from the repo by downloading clicking on the exe and downloading the one file. Github restricts uploads larger than 25MB and after making my changes its still ~38MB

Please try todays update

**Comment by codemasterv** [comment]
OK just added the release version. Should no longer cause that issue but does look like its hanging when building the patch. This is normal and let it sit and do its thing.

The new release version is 88kb and not ~50MB

**Comment by codemasterv** [comment]
closing this issue as the 88kb version seems to fix the lockup issue

If you run into anything else please let me know and I will address it and apply fixes

**Comment by OnSight79** [comment]
Hi can someone please help me as im having trouble opening the orbis pub cmd. 
It just flashes on and off the screen real quic, i have tried registry edit but that didnt work.
Im on windows 10 so please can someone help ?
Thanks
